functionsDirectory = "C:\\Users\\Erik\\Desktop\\112-energie-v1\\112-energie 23-08-2025\\112energie-v2\\netlify\\functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Erik\\Desktop\\112-energie-v1\\112-energie 23-08-2025\\112energie-v2"
publishOrigin = "config"
commandOrigin = "ui"
command = "# no build command"
functions = "C:\\Users\\Erik\\Desktop\\112-energie-v1\\112-energie 23-08-2025\\112energie-v2\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]